/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/circle.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]} />
        <group position={[-0.73, 0, 1.17]}>
          <mesh geometry={nodes.Sphere001.geometry} material={materials.Root} scale={0.35} />
        </group>
        <group position={[-0.54, 1.82, 3.57]} />
      </group>
    </group>
  )
}

useGLTF.preload('/circle.gltf')
