/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/city-gold.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.blocks.geometry} material={nodes.blocks.material} position={[0.33, 0.48, -0.08]} scale={0.35} />
      <mesh geometry={nodes.buildings.geometry} material={materials['Material.002']} position={[0.33, 0.48, -0.08]} scale={0.35} />
      <mesh geometry={nodes.coastline.geometry} material={nodes.coastline.material} position={[0.33, 0.48, -0.08]} scale={0.35} />
      <mesh geometry={nodes.domain.geometry} material={materials['Full Road Texture']} position={[0.33, 0.48, -0.08]} scale={0.35} />
      <mesh geometry={nodes.river.geometry} material={nodes.river.material} position={[0.33, 0.48, -0.08]} scale={0.35} />
      <mesh geometry={nodes.roads.geometry} material={nodes.roads.material} position={[0.33, 0.48, -0.08]} scale={0.35} />
      <mesh geometry={nodes.sea.geometry} material={nodes.sea.material} position={[0.33, 0.48, -0.08]} scale={0.35} />
    </group>
  )
}

useGLTF.preload('/city-gold.gltf')
