/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/city.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.blocks.geometry} material={nodes.blocks.material} />
      <mesh geometry={nodes.buildings.geometry} material={materials.Scuffed_Gold} />
      <mesh geometry={nodes.coastline.geometry} material={nodes.coastline.material} />
      <mesh geometry={nodes.domain.geometry} material={materials['Full Road Texture']} />
      <mesh geometry={nodes.river.geometry} material={nodes.river.material} />
      <mesh geometry={nodes.roads.geometry} material={nodes.roads.material} />
      <mesh geometry={nodes.sea.geometry} material={nodes.sea.material} />
    </group>
  )
}

useGLTF.preload('/city.gltf')
