/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Isaack - Tacko The 3D Guy (https://sketchfab.com/isaackgamma)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/bucket-hat-drip-and-swag-vol2-f170dd10c9e74991a5528b5c798d9d5b
title: Bucket Hat - Drip and Swag Vol.2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hat.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <primitive object={nodes._rootJoint} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hat.gltf')
